### ISSUE TITLE
Explore Angular Templates

### ISSUE THREAD

**Issue by frankbouchard** [AES-Outreach/Outreach-Wiki#25]
How can this be integrated into the project. https://demos.creative-tim.com/material-dashboard-angular2/dashboard#pablo

**Comment by pat-lego** [comment]
The user profile is a nice layout but most of the components are not usable for us and would require as much rework as it would be to design it from scratch. I feel that a template for the components (ie. a theme) would be nice to use and perhaps a user profile component but I have yet to find something that consists of just that. The current library would be heavy to implement since we would need to also import the remainder of the libraries
